---
title: "R Notebook"
output: html_notebook
---

 

```{r}

library(dplyr)
library(tidyr)
library(pheatmap)
library(reshape2)

library(readr)
library(clusterProfiler)
library(msigdbr)
library(ggplot2)
library(DT)
library(enrichplot)
library(DOSE)
library(ReactomePA)
library(tidyr)
library(dplyr)
library(org.Hs.eg.db)

options(bitmapType = "cairo")


```


```{r}





```


##State1

```{r}
mTF_st1_net <- read.csv("tf_tf_network_uw14_St1.csv", header = T)
mTF_netA <- read.csv("TF_TF_network_UW14_new.csv", header = T)
regulon_det <- read.csv("~/Miner_UWcohort/Miner_program_regulonDet.csv", row.names = 1)
St1_prog_regulon_det <- read.csv("~/Miner_UWcohort/St1_masterTF_program_regulonDet.csv", row.names = 1)
st1_mTF_regAct <- read.csv("~/Miner_UWcohort/St1_masterTF_regulonAct.csv", header = T, row.names = 1)
st1_mTF_ProgAct <- read.csv("~/Miner_UWcohort/St1_masterTF_programAct.csv", header = T, row.names = 1)
mTF_st1_listy <- mTF_netA %>% filter(State == "St_1") %>% select(TF) %>% distinct()
miner_prog_reg_Det <- read.csv("~/Miner_UWcohort/MINER_program_regulonState_Details.csv", header = T, row.names = 1)
regulonAct_all <- read.csv("~/Miner_UWcohort/State_regulonAct_all.csv", header = T, row.names = 1)
ProgAct_all <- read.csv("~/Miner_UWcohort/State_programAct_all.csv", header = T, row.names = 1)

```


```{r}
masterTF_net_St1_only <- mTF_st1_net %>% filter(Source %in% mTF_st1_listy$TF)
st1_progReg_det2 <-St1_prog_regulon_det %>% select(RegulonID,State,Program) %>% distinct()
st1_progReg_det3 <- merge(st1_progReg_det2, regulon_det, by.x = "RegulonID", by.y = "Regulon_ID")
st1_progReg_det5 <- merge(st1_progReg_det3, masterTF_net_St1_only, by.x = "Regulator_ID", by.y = "Source")
st1_progReg_det6 <- st1_progReg_det5 %>% select(RegulonID, State, Program, Regulator_ID, Target, Edge) %>% distinct()
St1_mTF_RegMiner_netA <- st1_progReg_det6 %>% select(Regulator_ID, Target, Edge)
St1_mTF_RegMiner_netB <- st1_progReg_det6 %>% select(Regulator_ID, Program)
St1_mTF_RegMiner_netC <- st1_progReg_det6 %>% select(Program, RegulonID)
colnames(St1_mTF_RegMiner_netA) <- c("Regulator", "Target", "Edge")
St1_mTF_RegMiner_netB$Edge <- c("Program")
St1_mTF_RegMiner_netC$Edge <- c("Regulon")
colnames(St1_mTF_RegMiner_netB) <- c("Regulator", "Target", "Edge")
colnames(St1_mTF_RegMiner_netB) <- c("Regulator", "Target", "Edge")
colnames(St1_mTF_RegMiner_netC) <- c("Regulator", "Target", "Edge")

St1_mTF_RegMiner_netABC <- rbind(St1_mTF_RegMiner_netA,St1_mTF_RegMiner_netB)
St1_mTF_RegMiner_netABC <- rbind(St1_mTF_RegMiner_netABC,St1_mTF_RegMiner_netC)
St1_mTF_RegMiner_netABC2 <-St1_mTF_RegMiner_netABC %>% distinct()

write.csv(St1_mTF_RegMiner_netABC2,"St1_masterTF_MinerNet_Ed.csv")

```


```{r}
for(g in 1:length(mTF_st1_listy$TF)){
st1_TF_TG <- St1_mTF_RegMiner_netA %>% filter(Regulator == mTF_st1_listy$TF[g]) %>% dplyr::select(Target) %>% distinct()

#mTF_pr_ct<- st1_progReg_det3 %>% filter(Regulator_ID %in% st1_sox5_TG$Target) %>% dplyr::select(Program) %>% distinct() %>% count()
  
mTF_rg_ct <- regulon_det %>% filter(Regulator_ID %in% st1_TF_TG$Target) %>% dplyr::select(Regulon_ID) %>% distinct() %>% count()
mTF_rg <- regulon_det %>% filter(Regulator_ID %in% st1_TF_TG$Target) %>% dplyr::select(Regulon_ID) %>% distinct()

mTF_pr_ct <- miner_prog_reg_Det %>% filter(State== "St_1") %>% filter(RegulonID %in% mTF_rg$Regulon_ID) %>% dplyr::select(Program) %>% distinct() %>% count()

mTF_rg_prCt <- cbind(mTF_st1_listy$TF[g],mTF_rg_ct$n, mTF_pr_ct$n)
colnames(mTF_rg_prCt) <- c("mTF","Regulon No","Program No")
mTF_st1_Det <- rbind(mTF_st1_Det,mTF_rg_prCt)
}

```



```{r}
mTF_st1_net_comb <- mTF_st1_net %>% select(Source, Target, Edge) %>% pivot_wider(names_from = Target, values_from = Edge)
mTF_st1_net_comb <- as.data.frame(mTF_st1_net_comb)
rownames(mTF_st1_net_comb) <- mTF_st1_net_comb$Source
mTF_st1_net_comb2 <- mTF_st1_net_comb[,-1]

pheatmap(mTF_st1_net_comb, cluster_cols = F, cluster_rows = F, angle_col = 90, color = c("lightblue","darkred"), breaks = c(-0.25,0,0.25), fontsize = 14)

mTF_st1_net_comb_mTFO <- mTF_st1_net %>% filter(Source %in% mTF_st1_listy$TF) %>% dplyr::select(Source, Target, Edge) %>% filter(Source %in% mTF_st1_listy$TF) %>% pivot_wider(names_from = Target, values_from = Edge)
mTF_st1_net_comb_mTFO <- as.data.frame(mTF_st1_net_comb_mTFO)
rownames(mTF_st1_net_comb_mTFO) <- mTF_st1_net_comb_mTFO$Source
mTF_st1_net_comb_mTFO2 <- mTF_st1_net_comb_mTFO[,-1]


pheatmap(mTF_st1_net_comb_mTFO3, cluster_cols = F, cluster_rows = F, angle_col = 90, color = colorRampPalette(c("red", "white", "green"))(9),breaks = c(-0.2,-0.15,-0.1,-0.05,0,0.05,0.1,0.15,0.2),fontsize = 18, na_col = "grey")

mTF_mTF_net_st1 <- mTF_st1_net_comb %>% filter(Source %in% mTF_st1_listy$TF) %>% select(mTF_st1_listy$TF)
pheatmap(mTF_mTF_rel_st1, cluster_cols = F, cluster_rows = F, angle_col = 90, color = c("lightblue","darkred"), breaks = c(-0.25,0,0.25), fontsize = 18)

```



##State2


```{r}
mTF_st2_net <- read.csv("tf_tf_network_st2_uw14.csv", header = T, row.names = 1)


```




```{r}

#mTF_st2_net <- read.csv("tf_tf_network_st2_uw14.csv", header = T, row.names = 1)
TF_TF_st2_net_comb <- mTF_st2_net %>% filter(Source %in% mTF_st2_listy$TF) %>% dplyr::select(Source, Target, Edge) %>% pivot_wider(names_from = Target, values_from = Edge)
TF_TF_st2_net_comb <- as.data.frame(TF_TF_st2_net_comb)
rownames(TF_TF_st2_net_comb) <- TF_TF_st2_net_comb$Source
TF_TF_st2_net_comb2 <- TF_TF_st2_net_comb[,-1]

pheatmap(TF_TF_st2_net_comb2, cluster_cols = F, cluster_rows = F, angle_col = 90, color = c("lightblue","darkred"), breaks = c(-0.25,0,0.25), fontsize = 14)

pheatmap(mTF_st5_net_comb_mTFO2, cluster_cols = F, cluster_rows = F, angle_col = 90, color = colorRampPalette(c("red", "white", "green"))(9), breaks = c(-0.2,-0.15,-0.1,-0.05,0,0.05,0.1,0.15,0.2), fontsize = 18, na_col = "grey")


mTF_st2_listy <- mTF_netA %>% filter(State == "St_2") %>% dplyr::select(TF) %>% distinct()
mTF_st2_net_comb_mTFO <- TF_TF_st2_net_comb %>% filter(Source %in% mTF_st2_listy$TF)
mTF_st2_net_comb_mTFO <- as.data.frame(mTF_st2_net_comb_mTFO)
rownames(mTF_st2_net_comb_mTFO) <- mTF_st2_net_comb_mTFO$Source
mTF_st2_net_comb_mTFO2 <- mTF_st2_net_comb_mTFO[,-1]

mTF_mTF_net_st2 <- TF_TF_st2_net_comb %>% filter(Source %in% mTF_st2_listy$TF) %>% dplyr::select(c("SOX9", "SOX8","POU3F3", "SOX4")) 


```


  Program n
1        6 5
2        2 3
3       15 3
4       18 3
5       29 3

```{r}


masterTF_net_St2_only <- mTF_st2_net %>% filter(Source %in% mTF_st2_listy$TF)
St2_prog_regulon_det <- miner_prog_reg_Det %>% filter(RegulonID %in% St2_regulonID$Regulon_ID & State == "St_2")
st2_progReg_det2 <- St2_prog_regulon_det %>% dplyr::select(RegulonID,State,Program) %>% distinct()
st2_progReg_det3 <- merge(st2_progReg_det2, regulon_det, by.x = "RegulonID", by.y = "Regulon_ID")
st2_progReg_det5 <- merge(st2_progReg_det3, masterTF_net_St2_only, by.x = "Regulator_ID", by.y = "Source")
st2_progReg_det6 <- st2_progReg_det5 %>% dplyr::select(RegulonID, State, Program, Regulator_ID, Target, Edge) %>% distinct()
St2_mTF_RegMiner_netA <- st2_progReg_det6 %>% dplyr::select(Regulator_ID, Target, Edge)
St2_mTF_RegMiner_netB <- st2_progReg_det6 %>% dplyr::select(Regulator_ID, Program)
St2_mTF_RegMiner_netC <- st2_progReg_det6 %>% dplyr::select(Program, RegulonID)
colnames(St2_mTF_RegMiner_netA) <- c("Regulator", "Target", "Edge")
St2_mTF_RegMiner_netB$Edge <- c("Program")
St2_mTF_RegMiner_netC$Edge <- c("Regulon")
colnames(St2_mTF_RegMiner_netB) <- c("Regulator", "Target", "Edge")
colnames(St2_mTF_RegMiner_netB) <- c("Regulator", "Target", "Edge")
colnames(St2_mTF_RegMiner_netC) <- c("Regulator", "Target", "Edge")

St2_mTF_RegMiner_netABC <- rbind(St2_mTF_RegMiner_netA,St2_mTF_RegMiner_netB)
St2_mTF_RegMiner_netABC <- rbind(St2_mTF_RegMiner_netABC,St2_mTF_RegMiner_netC)
St2_mTF_RegMiner_netABC2 <- St2_mTF_RegMiner_netABC %>% distinct()

write.csv(St2_mTF_RegMiner_netABC2,"St2_masterTF_MinerNet_Ed.csv")


```



```{r}
for(g in 1:length(mTF_st2_listy$TF)){
st2_TF_TG <- St2_mTF_RegMiner_netA %>% filter(Regulator == mTF_st2_listy$TF[g]) %>% dplyr::select(Target) %>% distinct()

#mTF_pr_ct<- st1_progReg_det3 %>% filter(Regulator_ID %in% st1_sox5_TG$Target) %>% dplyr::select(Program) %>% distinct() %>% count()
  
mTF_rg_ct <- regulon_det %>% filter(Regulator_ID %in% st2_TF_TG$Target) %>% dplyr::select(Regulon_ID) %>% distinct() %>% count()
mTF_rg <- regulon_det %>% filter(Regulator_ID %in% st2_TF_TG$Target) %>% dplyr::select(Regulon_ID) %>% distinct()

mTF_pr_ct <- miner_prog_reg_Det %>% filter(State== "St_2") %>% filter(RegulonID %in% mTF_rg$Regulon_ID) %>% dplyr::select(Program) %>% distinct() %>% count()

mTF_rg_prCt <- cbind(mTF_st2_listy$TF[g],mTF_rg_ct$n, mTF_pr_ct$n)
colnames(mTF_rg_prCt) <- c("mTF","Regulon No","Program No")
mTF_st2_Det <- rbind(mTF_st2_Det,mTF_rg_prCt)
}
```



## St_5

```{r}

mTF_st5_net <- read.csv("tf_tf_network_uw14R_st5.csv", header = T, row.names = 1)
mTF_netB <- read.csv("TF_TF_network_UW14R_new.csv", header = T)
St5_regulonID <- regulon_det %>% filter(Regulator_ID %in% mTF_st5_listy$TF) %>% dplyr::select(Regulon_ID)
St5_programID <- miner_prog_reg_Det %>% filter(RegulonID %in% St5_regulonID$Regulon_ID & State == "St_5")

masterTF_net_St5_only <- mTF_st5_net %>% filter(Source %in% mTF_st5_listy$TF)
St5_prog_regulon_det <- miner_prog_reg_Det %>% filter(RegulonID %in% St5_regulonID$Regulon_ID & State == "St_5")
st5_progReg_det2 <- St5_prog_regulon_det %>% dplyr::select(RegulonID,State,Program) %>% distinct()
st5_progReg_det3 <- merge(st5_progReg_det2, regulon_det, by.x = "RegulonID", by.y = "Regulon_ID")
st5_progReg_det5 <- merge(st5_progReg_det3, masterTF_net_St5_only, by.x = "Regulator_ID", by.y = "Source")
st5_progReg_det6 <- st5_progReg_det5 %>% dplyr::select(RegulonID, State, Program, Regulator_ID, Target, Edge) %>% distinct()
St5_mTF_RegMiner_netA <- st5_progReg_det6 %>% dplyr::select(Regulator_ID, Target, Edge)
St5_mTF_RegMiner_netB <- st5_progReg_det6 %>% dplyr::select(Regulator_ID, Program)
St5_mTF_RegMiner_netC <- st5_progReg_det6 %>% dplyr::select(Program, RegulonID)
colnames(St5_mTF_RegMiner_netA) <- c("Regulator", "Target", "Edge")
St5_mTF_RegMiner_netB$Edge <- c("Program")
St5_mTF_RegMiner_netC$Edge <- c("Regulon")
colnames(St5_mTF_RegMiner_netB) <- c("Regulator", "Target", "Edge")
colnames(St5_mTF_RegMiner_netB) <- c("Regulator", "Target", "Edge")
colnames(St5_mTF_RegMiner_netC) <- c("Regulator", "Target", "Edge")

St5_mTF_RegMiner_netABC <- rbind(St5_mTF_RegMiner_netA, St5_mTF_RegMiner_netB)
St5_mTF_RegMiner_netABC <- rbind(St5_mTF_RegMiner_netABC, St5_mTF_RegMiner_netC)
St5_mTF_RegMiner_netABC2 <- St5_mTF_RegMiner_netABC %>% distinct()

write.csv(St5_mTF_RegMiner_netABC2,"St5_masterTF_MinerNet_Ed.csv")

```



```{r}
TF_TF_st5_net_comb <- mTF_st5_net %>% dplyr::select(Source, Target, Edge) %>% pivot_wider(names_from = Target, values_from = Edge)
TF_TF_st5_net_comb <- as.data.frame(TF_TF_st5_net_comb)
rownames(TF_TF_st5_net_comb) <- TF_TF_st5_net_comb$Source
TF_TF_st5_net_comb2 <- TF_TF_st5_net_comb[,-1]

pheatmap(TF_TF_st5_net_comb2, cluster_cols = F, cluster_rows = F, angle_col = 90, color = c("lightblue","darkred"), breaks = c(-0.25,0,0.25), fontsize = 14)

#mTF_st2_listy <- mTF_netA %>% filter(State == "St_2") %>% dplyr::select(TF) %>% distinct()
mTF_st5_net_comb_mTFO <- mTF_st5_net %>% dplyr::select(Source, Target, Edge)%>% filter(Source %in% mTF_st5_listy$TF) %>% pivot_wider(names_from = Target, values_from = Edge)
mTF_st5_net_comb_mTFO <- as.data.frame(mTF_st5_net_comb_mTFO)
rownames(mTF_st5_net_comb_mTFO) <- mTF_st5_net_comb_mTFO$Source
mTF_st5_net_comb_mTFO2 <- mTF_st5_net_comb_mTFO[,-1]

pheatmap(mTF_st5_net_comb_mTFO2, cluster_cols = F, cluster_rows = F, angle_col = 90, color = c("lightblue","darkred"), breaks = c(-0.25,0,0.25), fontsize = 18)

pheatmap(mTF_st5_net_comb_mTFO2, cluster_cols = F, cluster_rows = F, angle_col = 90, color = colorRampPalette(c("red", "white", "green"))(9), breaks = c(-0.2,-0.15,-0.1,-0.05,0,0.05,0.1,0.15,0.2), fontsize = 18, na_col = "grey")


mTF_st5_net_comb_mTFO_comR <- mTF_st5_net %>% dplyr::select(Source, Target, Edge)%>% filter(Source %in% mTF_st5_listy$TF) %>%filter(Target %in% c("ETV1","KLF12","RFX3","MAZ","LMO2","MEIS2","NFIB","PRRX1","CREB5","IKZF2","RFX7","ID4")) %>% pivot_wider(names_from = Target, values_from = Edge)



```



##Revised analysis with median program activity instead of mean

```{r}

st1_mTF_ProgAct_PatPrmean2 <- st1_mTF_ProgAct %>% group_by(Program_ID) %>% mutate(meanact = mean(Prog.Activity))
st1_mTF_ProgAct_PatPrmedian <- st1_mTF_ProgAct %>% group_by(Program_ID) %>% mutate(medact = median(Prog.Activity))

st1_mTF_ProgAct_PatPrmean2 %>% filter(meanact > 0.2 ) %>% dplyr::select(Program_ID) %>% distinct()
# 1, 2, 4, 15, 33
st1_mTF_ProgAct_PatPrmedian %>% filter(medact > 0.2 ) %>% dplyr::select(Program_ID) %>% distinct()
# 1, 2, 15, 33
st1_med_overAct <- st1_mTF_ProgAct_PatPrmedian %>% filter(Program_ID %in% c(1,2,15,33))
#ggplot(st1_med_overAct, aes(x=Program_ID, y=Prog.Activity)) +  geom_boxplot(notch=TRUE, notchwidth = 0.8) +  geom_hline(yintercept=0, linetype="dashed", color = "red") + theme_classic() + theme(axis.text = element_text(size = 18), axis.title = element_text(size = 20)) + xlab("Program ID") + ylab("Program activity")


st1_mTF_ProgAct_PatPrmedian %>% filter(medact < -0.2 ) %>% dplyr::select(Program_ID) %>% distinct()
# 6, 26, 35, 32, 29, 5, 19, 31
st1_mTF_ProgAct_PatPrmean2  %>% filter(meanact < -0.2 ) %>% dplyr::select(Program_ID) %>% distinct()
# 6, 26, 35, 32, 29, 5, 19, 31
st1_med_underAct <- st1_mTF_ProgAct_PatPrmedian %>% filter(Program_ID %in% c(6,26,35,32,29,5,19,31))
st1_med_underAct$Program_ID <- as.factor(st1_med_underAct$Program_ID)
#ggplot(st1_med_underAct, aes(x=Program_ID, y=Prog.Activity)) +  geom_boxplot(notch=TRUE, notchwidth = 0.8) +  geom_hline(yintercept=0, linetype="dashed", color = "red") + theme_classic() + theme(axis.text = element_text(size = 18), axis.title = element_text(size = 20)) + xlab("Program ID") + ylab("Program activity")
##outlier cell states in some patients



st2_mTF_ProgAct_PatPrmean2 <- St2_mTF_program_act %>% group_by(Program_ID) %>% mutate(meanact = mean(Prog.Activity))
st2_mTF_ProgAct_PatPrmedian <- St2_mTF_program_act %>% group_by(Program_ID) %>% mutate(medact = median(Prog.Activity))


st2_mTF_ProgAct_PatPrmean2 %>% filter(meanact > 0.2 ) %>% dplyr::select(Program_ID) %>% distinct()
# 23, 28, 30, 2, 10, 15, 1, 4, 25, 18, 27, 32, 13
st2_mTF_ProgAct_PatPrmedian %>% filter(medact > 0.2 ) %>% dplyr::select(Program_ID) %>% distinct()
# 23, 28, 30, 2, 10, 15, 1, 4, 18, 27, 32, 13

st2_med_overAct <- st2_mTF_ProgAct_PatPrmedian %>% filter(Program_ID %in% c(23, 28, 30, 2, 10, 15, 1, 4, 18, 27, 32, 13))
st2_med_overAct$Program <- as.factor(st2_med_overAct$Program)
#ggplot(st2_med_overAct, aes(x=Program_ID, y=Prog.Activity)) +  geom_boxplot(notch=TRUE, notchwidth = 0.8) +  geom_hline(yintercept=0, linetype="dashed", color = "red") + theme_classic() + theme(axis.text = element_text(size = 18), axis.title = element_text(size = 20)) + xlab("Program ID") + ylab("Program activity")

st2_mTF_ProgAct_PatPrmedian %>% filter(medact < -0.2 ) %>% dplyr::select(Program_ID) %>% distinct()
# 5
st2_mTF_ProgAct_PatPrmean2 %>% filter(meanact < -0.2 ) %>% dplyr::select(Program_ID) %>% distinct()
# 5
st2_med_underAct <- st2_mTF_ProgAct_PatPrmedian %>% filter(Program_ID %in% c(5))
st2_med_underAct$Program_ID <- as.factor(st2_med_underAct$Program_ID)
#ggplot(st2_med_underAct, aes(x=Program_ID, y=Prog.Activity)) +  geom_boxplot(notch=TRUE, notchwidth = 0.8) +  geom_hline(yintercept=0, linetype="dashed", color = "red") + theme_classic() + theme(axis.text = element_text(size = 18), axis.title = element_text(size = 20)) + xlab("Program ID") + ylab("Program activity")

st5_mTF_ProgAct_PatPrmean2 <- St5_mTF_program_act %>% group_by(Program_ID) %>% mutate(meanact = mean(Prog.Activity))
st5_mTF_ProgAct_PatPrmedian <- St5_mTF_program_act %>% group_by(Program_ID) %>% mutate(medact = median(Prog.Activity))


st5_mTF_ProgAct_PatPrmean2 %>% filter(meanact > 0.2 ) %>% dplyr::select(Program_ID) %>% distinct()
# 36
st5_mTF_ProgAct_PatPrmedian %>% filter(medact > 0.2 ) %>% dplyr::select(Program_ID) %>% distinct()
# 36

st5_med_overAct <- st5_mTF_ProgAct_PatPrmedian %>% filter(Program_ID %in% c(36))
st5_med_overAct$Program <- as.factor(st5_med_overAct$Program)
#ggplot(st5_med_overAct, aes(x=Program_ID, y=Prog.Activity)) +  geom_boxplot(notch=TRUE, notchwidth = 0.8) +  geom_hline(yintercept=0, linetype="dashed", color = "red") + theme_classic() + theme(axis.text = element_text(size = 18), axis.title = element_text(size = 20)) + xlab("Program ID") + ylab("Program activity")

st5_mTF_ProgAct_PatPrmedian %>% filter(medact < -0.2 ) %>% dplyr::select(Program_ID) %>% distinct()
# 8 14 13 10 31 23 21 33  1 35  5 28  2  6 22 30 27 12  4 18 15  7 32 29 25
st5_mTF_ProgAct_PatPrmean2 %>% filter(meanact < -0.2 ) %>% dplyr::select(Program_ID) %>% distinct()
# 8 14 13 10 31 23 21 33  1 35  5 28  2  6 22 30 27 12  4 18 15  7 32 29 25
st5_med_underAct <- st5_mTF_ProgAct_PatPrmedian %>% filter(Program_ID %in% c(8, 14, 13, 10, 31, 23, 21, 33, 1, 35,  5, 28,  2,  6, 22, 30, 27, 12,  4, 18, 15,  7, 32, 29, 25))
st5_med_underAct$Program_ID <- as.factor(st5_med_underAct$Program_ID)
#ggplot(st5_med_underAct, aes(x=Program_ID, y=Prog.Activity)) +  geom_boxplot(notch=TRUE, notchwidth = 0.8) +  geom_hline(yintercept=0, linetype="dashed", color = "red") + theme_classic() + theme(axis.text = element_text(size = 18), axis.title = element_text(size = 20)) + xlab("Program ID") + ylab("Program activity")



```



```{r}

#mTF_st5_listy$TF
#mTF_st2_listy$TF
#mTF_st1_listy$TF

for(j in 1:length(mTF_st1_listy$TF)){
  pr_cnt <- st1_progReg_det6 %>% filter(Regulator_ID == mTF_st1_listy$TF[j]) %>% dplyr::select(Program) %>% distinct() %>% count()
  reg_cnt <- st1_progReg_det6 %>% filter(Regulator_ID == mTF_st1_listy$TF[j]) %>% dplyr::select(RegulonID) %>% distinct() %>% count()
  
  st1_tab <- cbind(mTF_st1_listy$TF[j], pr_cnt$n, reg_cnt$n)
  st1_tab2 <- rbind(st1_tab2, st1_tab)
}
colnames(st1_tab2) <- c("Regulator","Program count","Regulon count")

```


```{r}

for(j in 1:length(mTF_st2_listy$TF)){
  pr_cnt <- st2_progReg_det6 %>% filter(Regulator_ID == mTF_st2_listy$TF[j]) %>% dplyr::select(Program) %>% distinct() %>% count()
  reg_cnt <- st2_progReg_det6 %>% filter(Regulator_ID == mTF_st2_listy$TF[j]) %>% dplyr::select(RegulonID) %>% distinct() %>% count()
  st2_tab <- cbind(mTF_st2_listy$TF[j], pr_cnt$n, reg_cnt$n)
  st2_tab2 <- rbind(st2_tab2, st2_tab)
}
colnames(st2_tab2) <- c("Regulator","Program count","Regulon count")


```


```{r}

for(j in 1:length(mTF_st5_listy$TF)){
  pr_cnt <- st5_progReg_det6 %>% filter(Regulator_ID == mTF_st5_listy$TF[j]) %>% dplyr::select(Program) %>% distinct() %>% count()
  reg_cnt <- st5_progReg_det6 %>% filter(Regulator_ID == mTF_st5_listy$TF[j]) %>% dplyr::select(RegulonID) %>% distinct() %>% count()
  st5_tab <- cbind(mTF_st5_listy$TF[j], pr_cnt$n, reg_cnt$n)
  st5_tab2 <- rbind(st5_tab2, st5_tab)
}
colnames(st5_tab2) <- c("Regulator","Program count","Regulon count")


```


```{r}

for(g in 1:length(mTF_st5_listy$TF)){
st5_TF_TG <- St5_mTF_RegMiner_netA %>% filter(Regulator == mTF_st5_listy$TF[g]) %>% dplyr::select(Target) %>% distinct()

#mTF_pr_ct<- st1_progReg_det3 %>% filter(Regulator_ID %in% st1_sox5_TG$Target) %>% dplyr::select(Program) %>% distinct() %>% count()
  
mTF_rg_ct <- regulon_det %>% filter(Regulator_ID %in% st5_TF_TG$Target) %>% dplyr::select(Regulon_ID) %>% distinct() %>% count()
mTF_rg <- regulon_det %>% filter(Regulator_ID %in% st5_TF_TG$Target) %>% dplyr::select(Regulon_ID) %>% distinct()

mTF_pr_ct <- miner_prog_reg_Det %>% filter(State== "St_5") %>% filter(RegulonID %in% mTF_rg$Regulon_ID) %>% dplyr::select(Program) %>% distinct() %>% count()

mTF_rg_prCt <- cbind(mTF_st5_listy$TF[g],mTF_rg_ct$n, mTF_pr_ct$n)
colnames(mTF_rg_prCt) <- c("mTF","Regulon No","Program No")
mTF_st5_Det <- rbind(mTF_st5_Det,mTF_rg_prCt)
}

```


```{r}

s2Info <- st2_progReg_det6 %>% dplyr::select(State, Program, Regulator_ID) %>% distinct(.keep_all = T)
st2Info2 <- merge(s2Info, st2_medAct_tg, by.x = "Program", by.y = "Program_ID")
st2Info2 <- merge(st2Info2, st2_funksAl, by.x = "Program", by.y = "Program")
write.csv(st2Info2,"St2_programInfoActFunc.csv")
```

